import { Ingredient } from '../types/cookie';

export const ingredientsDatabase: Ingredient[] = [
  // FLOURS
  {
    id: 'flour-ap',
    name: 'All-Purpose Flour',
    category: 'flour',
    calories: 364,
    protein: 10.3,
    fat: 0.98,
    carbs: 76.3,
    fiber: 2.7,
    sugar: 0.3,
    sodium: 2,
    waterContent: 12,
    waterActivity: 0.6,
    proteinContent: 10.3,
    density: 0.528, // ~125g per cup
  },
  {
    id: 'flour-bread',
    name: 'Bread Flour',
    category: 'flour',
    calories: 361,
    protein: 13,
    fat: 1.7,
    carbs: 72,
    fiber: 2.4,
    sugar: 0.4,
    sodium: 2,
    waterContent: 11,
    waterActivity: 0.58,
    proteinContent: 13,
    density: 0.528,
  },
  {
    id: 'flour-cake',
    name: 'Cake Flour',
    category: 'flour',
    calories: 350,
    protein: 8,
    fat: 0.9,
    carbs: 77,
    fiber: 2.2,
    sugar: 0.2,
    sodium: 2,
    waterContent: 12,
    waterActivity: 0.6,
    proteinContent: 8,
    density: 0.506, // ~120g per cup
  },
  {
    id: 'flour-whole-wheat',
    name: 'Whole Wheat Flour',
    category: 'flour',
    calories: 340,
    protein: 13.7,
    fat: 1.9,
    carbs: 72,
    fiber: 10.7,
    sugar: 0.4,
    sodium: 5,
    waterContent: 11,
    waterActivity: 0.62,
    proteinContent: 13.7,
    density: 0.506,
  },

  // SUGARS
  {
    id: 'sugar-white',
    name: 'Granulated White Sugar',
    category: 'sugar',
    calories: 387,
    protein: 0,
    fat: 0,
    carbs: 100,
    fiber: 0,
    sugar: 100,
    sodium: 1,
    waterContent: 0.5,
    waterActivity: 0.11,
    sucroseEquivalence: 1.0,
    density: 0.845, // ~200g per cup
  },
  {
    id: 'sugar-brown',
    name: 'Brown Sugar',
    category: 'sugar',
    calories: 380,
    protein: 0.1,
    fat: 0,
    carbs: 98,
    fiber: 0,
    sugar: 97,
    sodium: 28,
    waterContent: 1.8,
    waterActivity: 0.59,
    sucroseEquivalence: 0.97,
    density: 0.932, // ~220g per cup packed
  },
  {
    id: 'sugar-powdered',
    name: 'Powdered Sugar',
    category: 'sugar',
    calories: 389,
    protein: 0,
    fat: 0,
    carbs: 100,
    fiber: 0,
    sugar: 100,
    sodium: 1,
    waterContent: 0.2,
    waterActivity: 0.08,
    sucroseEquivalence: 1.0,
  },
  {
    id: 'honey',
    name: 'Honey',
    category: 'sugar',
    calories: 304,
    protein: 0.3,
    fat: 0,
    carbs: 82.4,
    fiber: 0.2,
    sugar: 82.1,
    sodium: 4,
    waterContent: 17.1,
    waterActivity: 0.6,
    sucroseEquivalence: 1.3,
  },
  {
    id: 'corn-syrup',
    name: 'Corn Syrup',
    category: 'sugar',
    calories: 286,
    protein: 0,
    fat: 0,
    carbs: 77,
    fiber: 0,
    sugar: 31,
    sodium: 31,
    waterContent: 24,
    waterActivity: 0.7,
    sucroseEquivalence: 0.4,
  },

  // FATS
  {
    id: 'butter-unsalted',
    name: 'Unsalted Butter',
    category: 'fat',
    calories: 717,
    protein: 0.85,
    fat: 81.1,
    carbs: 0.06,
    fiber: 0,
    sugar: 0.06,
    sodium: 11,
    waterContent: 17.9,
    waterActivity: 0.97,
    fatContent: 81.1,
    density: 0.959, // ~227g per cup (2 sticks)
  },
  {
    id: 'butter-salted',
    name: 'Salted Butter',
    category: 'fat',
    calories: 717,
    protein: 0.85,
    fat: 81.1,
    carbs: 0.06,
    fiber: 0,
    sugar: 0.06,
    sodium: 643,
    waterContent: 17.9,
    waterActivity: 0.95,
    fatContent: 81.1,
    density: 0.959,
  },
  {
    id: 'oil-vegetable',
    name: 'Vegetable Oil',
    category: 'fat',
    calories: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    waterContent: 0,
    waterActivity: 0.05,
    fatContent: 100,
  },
  {
    id: 'shortening',
    name: 'Shortening',
    category: 'fat',
    calories: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    waterContent: 0,
    waterActivity: 0.05,
    fatContent: 100,
  },

  // EGGS
  {
    id: 'egg-whole',
    name: 'Whole Egg',
    category: 'egg',
    calories: 143,
    protein: 12.6,
    fat: 9.5,
    carbs: 0.7,
    fiber: 0,
    sugar: 0.4,
    sodium: 142,
    waterContent: 76,
    waterActivity: 0.97,
  },
  {
    id: 'egg-white',
    name: 'Egg White',
    category: 'egg',
    calories: 52,
    protein: 10.9,
    fat: 0.2,
    carbs: 0.7,
    fiber: 0,
    sugar: 0.7,
    sodium: 166,
    waterContent: 88,
    waterActivity: 0.98,
  },
  {
    id: 'egg-yolk',
    name: 'Egg Yolk',
    category: 'egg',
    calories: 322,
    protein: 15.9,
    fat: 26.5,
    carbs: 3.6,
    fiber: 0,
    sugar: 0.6,
    sodium: 48,
    waterContent: 52,
    waterActivity: 0.96,
  },

  // LEAVENERS
  {
    id: 'baking-soda',
    name: 'Baking Soda',
    category: 'leavener',
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 27360,
    waterContent: 0,
    waterActivity: 0.05,
  },
  {
    id: 'baking-powder',
    name: 'Baking Powder',
    category: 'leavener',
    calories: 53,
    protein: 0,
    fat: 0,
    carbs: 27.7,
    fiber: 0.2,
    sugar: 0,
    sodium: 10600,
    waterContent: 2,
    waterActivity: 0.1,
  },

  // LIQUIDS
  {
    id: 'milk-whole',
    name: 'Whole Milk',
    category: 'liquid',
    calories: 61,
    protein: 3.2,
    fat: 3.3,
    carbs: 4.8,
    fiber: 0,
    sugar: 5.1,
    sodium: 43,
    waterContent: 88,
    waterActivity: 0.99,
  },
  {
    id: 'water',
    name: 'Water',
    category: 'liquid',
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    waterContent: 100,
    waterActivity: 1.0,
  },
  {
    id: 'vanilla-extract',
    name: 'Vanilla Extract',
    category: 'liquid',
    calories: 288,
    protein: 0.1,
    fat: 0.1,
    carbs: 12.7,
    fiber: 0,
    sugar: 12.7,
    sodium: 9,
    waterContent: 52,
    waterActivity: 0.9,
  },

  // CHOCOLATE
  {
    id: 'chocolate-chips-semisweet',
    name: 'Semi-Sweet Chocolate Chips',
    category: 'chocolate',
    calories: 479,
    protein: 4.2,
    fat: 27.8,
    carbs: 63.1,
    fiber: 5.6,
    sugar: 53.6,
    sodium: 11,
    waterContent: 1.3,
    waterActivity: 0.4,
    sucroseEquivalence: 0.7,
  },
  {
    id: 'chocolate-chips-dark',
    name: 'Dark Chocolate Chips',
    category: 'chocolate',
    calories: 501,
    protein: 5.5,
    fat: 32.4,
    carbs: 57.9,
    fiber: 8,
    sugar: 43.1,
    sodium: 12,
    waterContent: 1.2,
    waterActivity: 0.35,
    sucroseEquivalence: 0.6,
  },
  {
    id: 'cocoa-powder',
    name: 'Cocoa Powder (Unsweetened)',
    category: 'chocolate',
    calories: 228,
    protein: 19.6,
    fat: 13.7,
    carbs: 57.9,
    fiber: 33.2,
    sugar: 1.8,
    sodium: 21,
    waterContent: 3,
    waterActivity: 0.3,
  },

  // NUTS
  {
    id: 'walnuts',
    name: 'Walnuts (Chopped)',
    category: 'nut',
    calories: 654,
    protein: 15.2,
    fat: 65.2,
    carbs: 13.7,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 2,
    waterContent: 4.1,
    waterActivity: 0.5,
  },
  {
    id: 'pecans',
    name: 'Pecans (Chopped)',
    category: 'nut',
    calories: 691,
    protein: 9.2,
    fat: 72,
    carbs: 13.9,
    fiber: 9.6,
    sugar: 4,
    sodium: 0,
    waterContent: 3.5,
    waterActivity: 0.45,
  },
  {
    id: 'almonds',
    name: 'Almonds (Sliced)',
    category: 'nut',
    calories: 579,
    protein: 21.2,
    fat: 49.9,
    carbs: 21.6,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 1,
    waterContent: 4.4,
    waterActivity: 0.5,
  },

  // OTHER
  {
    id: 'salt',
    name: 'Salt',
    category: 'other',
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    sodium: 38758,
    waterContent: 0,
    waterActivity: 0.05,
  },
];
